In [1]:
import sys
import numpy as np

## Basics Arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Array Types

In [11]:
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('float64')

In [13]:
c = np.array(['a', 'b', 'c'])

In [14]:
c.dtype

dtype('<U1')

## Dimensions and Shapes

In [15]:
A = np.array([[1,2,3],
              [4,5,6]
             ])

In [16]:
A.shape

(2, 3)

In [17]:
A.size

6

In [18]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [19]:
B.shape

(2, 2, 3)

In [20]:
B[0,0,0]

12

In [21]:
B[0,1,0]

9

In [22]:
B.size

12

In [23]:
B.ndim

3

## Indexing and Slicing of Matrices

In [24]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])

In [25]:
A[1]

array([4, 5, 6])

In [26]:
A[1][0]

4

In [27]:
A[1,0]

4

In [28]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [30]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [31]:
A[:2,2:]

array([[3],
       [6]])

In [32]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
A[1] = np.array([10, 10, 10])

In [34]:
print(A[1])

[10 10 10]


In [35]:
A[2] = 90

In [36]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [90, 90, 90]])

## Summary statistics

In [37]:
a = np.array([1, 2, 3, 4])

In [38]:
a.sum()

10

In [39]:
a.mean()

2.5

In [40]:
a.std()

1.118033988749895

In [41]:
a.var()

1.25

In [42]:
A.sum()

306

In [43]:
A.mean()

34.0

In [44]:
A.sum(axis=0)

array([101, 102, 103])

In [45]:
A.sum(axis=1)

array([  6,  30, 270])

## Broadcasting and Vectorized operations

In [46]:
a = np.arange(4)

In [47]:
a

array([0, 1, 2, 3])

In [48]:
a + 10

array([10, 11, 12, 13])

In [49]:
a * 10

array([ 0, 10, 20, 30])

In [50]:
b = np.array([10, 10, 10, 10])

In [51]:
a + b

array([10, 11, 12, 13])

## Boolean arrays

In [52]:
a[[True, False, False, True]]

array([0, 3])

In [53]:
a >= 2

array([False, False,  True,  True])

In [54]:
a[a >= 2]

array([2, 3])

In [55]:
a[a > a.mean()]

array([2, 3])

In [56]:
a[~(a > a.mean())]

array([0, 1])

## Linear Algebra

In [57]:
B = np.array([[1,2],
              [4,5],
              [7,8]
             ])

In [58]:
A.dot(B)

array([[  30,   36],
       [ 120,  150],
       [1080, 1350]])

In [59]:
A @ B

array([[  30,   36],
       [ 120,  150],
       [1080, 1350]])

In [60]:
B.T

array([[1, 4, 7],
       [2, 5, 8]])

In [61]:
B.T @ A

array([[671, 672, 673],
       [772, 774, 776]])

## Useful Numpy functions

In [62]:
np.random.random(size=2)

array([0.27179225, 0.19516284])

In [63]:
np.random.normal(size=2)

array([0.50736351, 0.37939419])

In [64]:
np.random.rand(2,4)

array([[0.85249422, 0.8151128 , 0.66046713, 0.70473152],
       [0.85642223, 0.2594173 , 0.93643531, 0.38457942]])

In [65]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [69]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [71]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [73]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [74]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [75]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [76]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(8, 4, k= -3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [83]:
"Hello World"[6]

'W'