In [2]:
import sys
import numpy as np

## Basics Arrays

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Array Types

In [12]:
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [14]:
c = np.array(['a', 'b', 'c'])

In [15]:
c.dtype

dtype('<U1')

## Dimensions and Shapes

In [16]:
A = np.array([[1,2,3],
              [4,5,6]
             ])

In [17]:
A.shape

(2, 3)

In [18]:
A.size

6

In [19]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [20]:
B.shape

(2, 2, 3)

In [21]:
B[0,0,0]

12

In [22]:
B[0,1,0]

9

In [23]:
B.size

12

In [25]:
B.ndim

3

## Indexing and Slicing of Matrices

In [26]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])

In [27]:
A[1]

array([4, 5, 6])

In [28]:
A[1][0]

4

In [29]:
A[1,0]

4

In [30]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [33]:
A[:2,2:]

array([[3],
       [6]])

In [34]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
A[1] = np.array([10, 10, 10])

In [37]:
print(A[1])

[10 10 10]


In [38]:
A[2] = 90

In [39]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [90, 90, 90]])

## Summary statistics

In [40]:
a = np.array([1, 2, 3, 4])

In [42]:
a.sum()

10

In [43]:
a.mean()

2.5

In [44]:
a.std()

1.118033988749895

In [45]:
a.var()

1.25

In [46]:
A.sum()

306

In [47]:
A.mean()

34.0

In [48]:
A.sum(axis=0)

array([101, 102, 103])

In [49]:
A.sum(axis=1)

array([  6,  30, 270])

## Broadcasting and Vectorized operations

In [50]:
a = np.arange(4)

In [51]:
a

array([0, 1, 2, 3])

In [52]:
a + 10

array([10, 11, 12, 13])

In [53]:
a * 10

array([ 0, 10, 20, 30])

In [54]:
b = np.array([10, 10, 10, 10])

In [55]:
a + b

array([10, 11, 12, 13])

## Boolean arrays

In [57]:
a[[True, False, False, True]]

array([0, 3])

In [58]:
a >= 2

array([False, False,  True,  True])

In [59]:
a[a >= 2]

array([2, 3])

In [60]:
a[a > a.mean()]

array([2, 3])

In [61]:
a[~(a > a.mean())]

array([0, 1])

## Linear Algebra

In [66]:
B = np.array([[1,2],
              [4,5],
              [7,8]
             ])

In [67]:
A.dot(B)

array([[  30,   36],
       [ 120,  150],
       [1080, 1350]])

In [68]:
A @ B

array([[  30,   36],
       [ 120,  150],
       [1080, 1350]])

In [69]:
B.T

array([[1, 4, 7],
       [2, 5, 8]])

In [70]:
B.T @ A

array([[671, 672, 673],
       [772, 774, 776]])

## Size of objects in Memory