In [1]:
import sys
import numpy as np

## Arrays Basicos

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Tipos Arrays

In [13]:
a.dtype

dtype('int64')

In [14]:
b.dtype

dtype('float64')

In [15]:
c = np.array(['a', 'b', 'c'])

In [16]:
c.dtype

dtype('<U1')

## Dimensions and Shapes

In [19]:
A = np.array([[1,2,3],
              [4,5,6]
             ])

In [18]:
A.shape

(2, 3)

In [20]:
A.size

6

In [22]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [23]:
B.shape

(2, 2, 3)

In [24]:
B[0,0,0]

12

In [28]:
B[0,1,0]

9